# -*- coding: utf-8 -*-
"""spam_mail_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ARQQFDY18c5hRyQv4gxJATHyJa_aIZlr
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/spam.csv', encoding='ISO-8859-1')

df.head()

df.tail()

df.sample(5)

df.shape

df.info()

df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace= True)

df.info()

df.rename(columns={'v1':'Output','v2':'Text'},inplace=True)

df.head(15)

from sklearn.preprocessing import LabelEncoder
label= LabelEncoder()

df['Output']=label.fit_transform(df['Output'])

df.sample(5)

df.isnull().sum()

df.duplicated().sum()

df=df.drop_duplicates(keep='first')

df.shape

value=df['Output'].value_counts()

import matplotlib.pyplot as plt
plt.pie(value,labels=['ham','spam'],autopct="%0.2f")
plt.show()

import nltk

!pip install nltk

nltk.download('punkt')

df['Text_char']=df['Text'].apply(len)

df['Text_word']=df['Text'].apply(lambda x:len(nltk.word_tokenize(x)))

df['Text_sen']=df['Text'].apply(lambda x:len(nltk.sent_tokenize(x)))

df

df[df['Output']==0][['Text_char','Text_word','Text_sen']].describe()

df[df['Output']==1][['Text_char','Text_word','Text_sen']].describe()

import seaborn as sns

plt.figure(figsize=(12,8))

sns.histplot(df[df['Output']==0]['Text_char'])
sns.histplot(df[df['Output']==1]['Text_char'],color='red')

sns.histplot(df[df['Output']==0]['Text_word'])
sns.histplot(df[df['Output']==1]['Text_word'],color='red')

sns.pairplot(df,hue='Output')

sns.heatmap(df.corr(),annot=True)

